.\" man: PHP-Markdown-Extended Developer Manual
.\" man-name: markdown-extended-api
.\" section: 7
.\" author: Pierre Cassat
.\" date: 2015-04-16
.\" version: 0.1.1-dev
.TH  "markdown-extended-api" "7" "2015-04-16" "Version 0.1.1-dev" "PHP-Markdown-Extended Developer Manual"
.SH NAME
.PP
Markdown-Extended-PHP API - Developer documentation of the internal API of the "piwi/markdown-extended" package.
.PP
The whole API is stored in the `\fS\\MarkdownExtended\\API\fP` namespace and is a set of interfaces
you must implement to use or override the parser or some of its objects.
.SH PARSER OPTIONS
.PP
The parser can accept a large set of options to customize or adapt the final
rendering. For a complete list, please see the `\fSgetDefaults()\fP` method
of the `\fS\\MarkdownExtended\\MarkdownExtended\fP` class <http://docs.ateliers-pierrot.fr/markdown-extended/MarkdownExtended/MarkdownExtended.html>.
.PP
Below is a review of interesting basic options:
.TP
template
Type: bool / 'auto' / file path
Default: `\fSfalse\fP` if the content has no metadata / `\fStrue\fP` otherwise
If it is `\fStrue\fP`, the default (basic) template is used, otherwise, the template
defined at `\fSfile path\fP` will be used. The default value is `\fSauto\fP`, which let the
parser choose if a template seems required (basically if the parsed content has
metadata or not). You can set it on `\fSfalse\fP` to never use a template.
.TP
config_file
Type: file path
Default: `\fSnull\fP`
Define a configuration file to overwrite defaults ; configuration files may be
in INI <http://en.wikipedia.org/wiki/INI_file>, JSON <http://json.org/> or 
raw PHP array <http://php.net/array> formats (it must return an array).
.TP
output_format
Type: string
Default: `\fShtml\fP`
The output format to use to build final rendering.
.TP
output
Type: string
Default: `\fSnull\fP`
.SH LIFE-CYCLE
.PP
The full schema of a Markdown parser usage could be:
.RS

.EX
[source file content]   [options]    
.br
       ||                  ||
.br
       \\/                  \\/
.br
---------------        ----------                            -------------------
.br
|  MD SOURCE  |   =>   | PARSER |   =>  [output format]  =>  | FORMATTED RESULT |
.br
---------------        ----------                            -------------------
.br
       /\\                  /\\                                         ||
.br
       ||                  ||                                         \\/
.br
    [string]        [ configuration ]                           [special info]
.EE
.RE
.PP
The original Markdown source can be either a buffered string (a form field for example)
or the content of a Markdown file
.PP
We want to parse the source content with a hand on options used during this parsing
(no need to parse metadata in a content that will never have some for example)
.PP
Finally, we want to get a formatted content and to be able to retrieve certain information
from it, such as its metadata, its menu or the footnotes of the whole parsed result
.PP
Additionally, it would be best that we can obtain a full formatted result simply but
can also pass this result through a template builder to construct a complex final string
.SH PARSER API
.PP
The public direct parser's access is the `\fS\\MarkdownExtended\\MarkdownExtended\fP`
object. It handles transformation and constructs dependencies. It returns a
parsed content as a `\fS\\MarkdownExtended\\Content\fP` object implementing the API
interface `\fS\\MarkdownExtended\\API\\ContentInterface\fP`. The rendered final format
transformations are done by an object implementing the API interface
`\fS\\MarkdownExtended\\API\\OutputFormatInterface\fP` which is called and managed
by the `\fS\\MarkdownExtended\\OutputFormatBag\fP` object. Internal available formats
are stored in the `\fS\\MarkdownExtended\\OutputFormat\fP` namespace. The filters applied
during content's parsing are managed by the `\fS\\MarkdownExtended\\Grammar\\Lexer\fP`
object, which actually call various "gamuts" methods or classes using the
`\fS\\MarkdownExtended\\Grammar\\GamutsLoader\fP` object. Each filter gamut is an
object implementing the API interface `\fS\\MarkdownExtended\\API\\GamutInterface\fP`.
The parser can load parsed content in a template file using an object implementing
the API interface `\fS\\MarkdownExtended\\API\\TemplateInterface\fP` and defaults to
the `\fS\\MarkdownExtended\\Templater\fP` object.
.PP
Finally, the internal central service container registering all the objects
involved in the parsing process is the `\fS\\MarkdownExtended\\API\\Kernel\fP`, which
only contains static methods.
.SS Public \fIMarkdownExtended\fP
.PP
The public `\fS\\MarkdownExtended\\MarkdownExtended\fP` object follows a simple static API:
.RS

.EX
\\MarkdownExtended\\MarkdownExtended::parse( content/file path , options ) : \\MarkdownExtended\\Content
.br

.br
\\MarkdownExtended\\MarkdownExtended::parseString( content , options ) : \\MarkdownExtended\\Content
.br

.br
\\MarkdownExtended\\MarkdownExtended::parseFile( file path , options ) : \\MarkdownExtended\\Content
.EE
.RE
.PP
These methods actually distribute the "real" work to the `\fS\\MarkdownExtended\\Parser\fP` 
object, which can be used as a literal procedural object like:
.RS

.EX
$parser = new \\MarkdownExtended\\Parser( options );
.br

.br
$content = $parser->transform( source string );
.br

.br
$content = $parser->transformSource( source file path );
.EE
.RE
.SS The \fIContent\fP object
.PP
The transformation process of the parser returns an object implementing interface
`\fS\\MarkdownExtended\\API\\ContentInterface\fP`. You can define your own object by passing
it directly to the `\fS\\MarkdownExtended\\MarkdownExtended\fP` parse methods (instead of a
raw string or file name).
.PP
The content object API allows to access each "block" of content and
to write the object directly:
.RS

.EX
string  Content::__toString()
.br
array   Content::__toArray()
.br

.br
string  Content::getContent()
.br

.br
string  Content::getCharset()
.br
string  Content::getTitle()
.br
string  Content::getBody()
.br
array   Content::getNotes()
.br
array   Content::getMetadata()
.br

.br
string  Content::getNotesFormatted()
.br
string  Content::getMetadataFormatted()
.br

.br
string  Content::getSource()
.br
array   Content::getParsingOptions()
.EE
.RE
.SS The \fIFilters\fP objects
.PP
A filter must implement the `\fS\\MarkdownExtended\\API\\GamutInterface\fP` interface 
and may extend the `\fS\\MarkdownExtended\\Grammar\\Filter\fP` object:
.RS

.EX
Filter->getDefaultMethod()
.br
Filter->transform( text )
.EE
.RE
.PP
Filters stacks to run during transformation are defined in the `\fSxxx_gamut\fP` items
of the configuration.
.SS The \fIOutputFormat\fP rendering
.PP
An output format renderer must implement the `\fS\\MarkdownExtended\\API\\OutputFormatInterface\fP`
interface defines some basic methods to build a content:
.RS

.EX
OutputFormat->buildTag( tag_name, content = null, array attributes = array() )
.br

.br
OutputFormat->getTagString( content, tag_name, array attributes = array() )
.EE
.RE
.SS The \fITemplate\fP renderer
.PP
A template object must implement the `\fS\\MarkdownExtended\\API\\TemplateInterface\fP`
interface, which contains one single method:
.RS

.EX
Template->parse( ContentInterface )
.EE
.RE
.SS The app's \fIKernel\fP
.PP
It acts like a service container:
.RS

.EX
\\MarkdownExtended\\Kernel->get('MarkdownExtended')
.br
\\MarkdownExtended\\Kernel->get('Content')
.br
\\MarkdownExtended\\Kernel->get('ContentCollection')
.br
\\MarkdownExtended\\Kernel->get('Lexer')
.br
\\MarkdownExtended\\Kernel->get('Grammar\\GamutLoader')
.br
\\MarkdownExtended\\Kernel->get('OutputFormatBag')
.br
\\MarkdownExtended\\Kernel->get('Template')
.br
\\MarkdownExtended\\Kernel->get('DomId')
.EE
.RE
.PP
It also acts like a configuration setter/getter:
.RS

.EX
\\MarkdownExtended\\Kernel::setConfig( index.subindex , value )
.br
\\MarkdownExtended\\Kernel::addConfig( index.subindex , value )
.br
\\MarkdownExtended\\Kernel::getConfig( index.subindex )
.EE
.RE
.SH SEE ALSO
.PP
An online documentation of last stable version is available at
<http://docs.ateliers-pierrot.fr/markdown-extended/>.
.PP
php(1), pcre(3), markdown-extended(3)
