#
# This file is part of the PHP-Markdown-Extended package.
#
# Copyright (c) 2008-2024, Pierre Cassat (me at picas dot fr) and contributors
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
languages:
  PHP: true
exclude_paths:
  - build/*
  - demo/*
  - dev/*
  - doc/*
  - man/*
  - phpdoc/*
  - src/MarkdownExtendedDev/*
  - tests/*
  - .php-cs-fixer.php
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR12"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,codesize,naming"
