#
# This file is part of the PHP-Markdown-Extended package.
#
# Copyright (c) 2008-2015, Pierre Cassat (me at picas dot fr) and contributors
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "master"
  - name: "dev"
  - name: "release-*"
    prerelease: "alpha"

plugins:
  - path: "@semantic-release/commit-analyzer"
  - path: "@semantic-release/release-notes-generator"
    commit: "/commit"
  - path: "@semantic-release/github"
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
    changelogTitle: "# Markdown Extended changelog"
  - path: "@semantic-release/git"
    assets:
      - "CHANGELOG.md"
    message: |
      chore(release): ${nextRelease.version}

      ${nextRelease.notes}
  - path: "@semantic-release/exec"
    verifyReleaseCmd: "echo \"${nextRelease.version}\" > /tmp/next_release"
  - path: "@saithodev/semantic-release-backmerge"
    backmergeBranches:
      - from: "master"
        to: "dev"
