.TH  "" "3" "" "" ""
.PP
[A5.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque \fIornare ipsum egestas ac\fP. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed \fBmalesuada orci id felis\fP consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu laoreet. Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, \fIsodales eget lacinia id\fP, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce imperdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, \fBplacerat eu odio et\fP, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc \fItincidunt vehicula ullamcorper\fP. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl,
scelerisque \fIornare ipsum egestas ac\fP. Vivamus laoreet erat purus, id tincidunt ipsum
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed \fBmalesuada orci id felis\fP consectetur auctor. Vestibulum
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante
sagittis, ut aliquam arcu laoreet. Etiam luctus ligula sit amet libero porta ullamcorper.
Phasellus nisi tortor, \fIsodales eget lacinia id\fP, tincidunt ac orci. Nulla scelerisque elit
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et
mauris lacinia pulvinar. Suspendisse potenti.
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus
ornare, id sollicitudin tellus facilisis. Fusce imperdiet dignissim augue, a sollicitudin
ligula sagittis in. Nam dolor leo, \fBplacerat eu odio et\fP, fermentum hendrerit justo. Fusce
eu lorem sed leo gravida facilisis. Nunc \fItincidunt vehicula ullamcorper\fP. Phasellus aliquet
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[A6.mde]
An abbreviation is written like a \fIreference\fP (§§ <#D3>) with a leading \fIasterisk\fP `\fS*\fP`:
.RS
.IP \(bu 
the abbreviation term at the beginning of the line between \fIbrackets\fP `\fS[\fP` and `\fS]\fP` and with:

.RS
.IP \(bu 
a leading \fIasterisk\fP `\fS*\fP` (without space)
.IP \(bu 
a trailing \fIcolon\fP `\fS:\fP` (without space)
.RE

.IP \(bu 

then the full text of the abbreviation

*[HTML (
.SM Hyper Text Markup Language
)]: Hyper Text Markup Language

.RE
.PP
Links can be written \fIinline\fP in the text, separated in two parts:
.RS
.IP \(bu 
the link text between \fIbrackets\fP `\fS[\fP` and `\fS]\fP`
.IP \(bu 

then, between \fIparenthesis\fP `\fS(\fP` and `\fS)\fP`, the URL of the link (relative or absolute) and 
an OPTIONAL title wrapped in \fIdouble-quotes\fP `\fS"\fP` followed by an OPTIONAL list of attributes (§§ <#D6>).

a simple link <http://test.com/>

a link with a title <http://test.com/>

[a link with a title and some attributes](http://test.com/ "My optional title" attribute1=value attribute2=value)

.RE
.PP
Images can be written \fIinline\fP in the text, separated in two parts:
.RS
.IP \(bu 
the image alternated text between \fIbrackets\fP `\fS[\fP` and `\fS]\fP` preceded by an \fIexclamation point\fP `\fS!\fP`
.IP \(bu 

then, between \fIparenthesis\fP `\fS(\fP` and `\fS)\fP`, the URL of the image (relative or absolute) and an 
OPTIONAL title wrapped in \fIdouble-quotes\fP `\fS"\fP` followed by an OPTIONAL list of attributes (§§ <#D6>).







.RE
.PP
A meta-data is added writing it at the very top of the document (without any blank line from
the top) as a `\fSvar: val\fP` pair:
.RS
.IP \(bu 
the meta-data name is written at the beginning of the line, followed by a \fIcolon\fP `\fS:\fP` and a \fIspace\fP
.IP \(bu 

the meta-data content can be multi-line

author: John Doe

.RE
.PP
A \fIcitation note\fP is written like a classic footnote but:
.RS
.IP \(bu 
the ID of the note is constructed in two parts like `\fS[p. XX][#Doe:1991]\fP`:

.RS
.IP \(bu 
the page number between \fIbrackets\fP `\fS[\fP` and `\fS]\fP` (this part is OPTIONAL)
.IP \(bu 
the reference ID, preceded by a \fIhash mark\fP `\fS#\fP`
.RE

.IP \(bu 

the note content follows the same rules as for classic footnotes, but the \fIcircumflex\fP
is replaced by a \fIhash mark\fP `\fS#\fP`.

Paragraph with a citation note [p. XX, [^Doe:1991]].

...

[#Doe:1991]: FirstName LastName (October 5, 1991). \fITitle of the work\fP.
edition for instance ... (Web link) Retrieved September 30, 2011.

.RE
.PP
[B2a.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque \fIornare ipsum egestas ac\fP. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed \fBmalesuada orci id felis\fP consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu laoreet. Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, \fIsodales eget lacinia id\fP, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce imperdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, \fBplacerat eu odio et\fP, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc \fItincidunt vehicula ullamcorper\fP. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[B2b.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque \fIornare ipsum egestas ac\fP. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed \fBmalesuada orci id felis\fP consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu laoreet. Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, \fIsodales eget lacinia id\fP, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce imperdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, \fBplacerat eu odio et\fP, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc \fItincidunt vehicula ullamcorper\fP. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[B2c.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque \fIornare_ipsum_egestas ac\fP. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed \fBmalesuada orci id felis\fP consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu laoreet. Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, \fIsodales_eget lacinia_id\fP, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce imperdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, \fBplacerat_eu odio_et\fP, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc \fItincidunt vehicula ullamcorper\fP. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque \fIornare\fPipsum\fIegestas ac\fP. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed \fBmalesuada orci id felis\fP consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu laoreet. Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, \fIsodales\fPeget lacinia\fIid\fP, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce imperdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, \fBplacerat\fIeu odio\fPet\fP, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc \fItincidunt vehicula ullamcorper\fP. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[B3.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[B4.mde]
Lorem ipsum `\fSdolor sit amet\fP`, consectetur `\fS$adipiscing\fP` elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus `\fSlaoreet _erat_ purus\fP`, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue.
[B5a.mde]
Lorem ipsum dolor sit amet consectetur adipiscing elit.
.PP
Lorem ipsum http://aboutmde.org/loremipsum/lorem-ipsum.html dolor sit amet consectetur adipiscing elit.
.PP
Lorem ipsum <http://aboutmde.org/loremipsum/lorem-ipsum.html> dolor sit amet consectetur adipiscing elit.
[B5b.mde]
Lorem ipsum <http://aboutmde.org/loremipsum/lorem-ipsum.html> dolor sit amet consectetur adipiscing elit.
.PP
Lorem ipsum <loremipsum/lorem-ipsum.html> dolor sit amet consectetur adipiscing elit.
.PP
[B5c.mde]
Lorem ipsum dolor sit amet <http://aboutmde.org/loremipsum/lorem-ipsum.html> elit.
.PP
Lorem ipsum dolor sit amet <http://aboutmde.org/loremipsum/lorem-ipsum.html> elit.
.PP
Lorem ipsum dolor sit amet <http://aboutmde.org/loremipsum/lorem-ipsum.html> elit.
.PP
[B5d.mde]
Lorem ipsum dolor sit amet <#consectetur> adipiscing elit.
[B5f.mde]
Lorem ipsum dolor sit amet <http://aboutmde.org/loremipsum/lorem-ipsum.html> elit.
.PP
Lorem ipsum dolor sit amet <http://aboutmde.org/loremipsum/lorem-ipsum.html> elit.
.PP
Lorem ipsum [dolor sit amet][dolor sit amet3] elit.
.PP
Lorem ipsum dolor sit amet4 <http://aboutmde.org/loremipsum/lorem-ipsum.html> elit.
.PP
[B6a.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. 
Vivamus laoreet erat purus, id tincidunt ipsum  malesuada a. Morbi at est sed mauris blandit 
congue.
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. 
Vivamus laoreet erat purus, id tincidunt ipsum  malesuada a. Morbi at est sed mauris blandit 
congue.
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. 
Vivamus laoreet erat purus, id tincidunt ipsum  malesuada a. Morbi at est sed mauris blandit 
congue.
.PP
[B6b.mde]
Lorem ipsum  elit.
.PP
Lorem ipsum  elit.
.PP
Lorem ipsum ![dolor sit amet3][dolor sit amet3] elit.
.PP
Lorem ipsum  elit.
.PP
[B8.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac: [\alpha = (t_1 - t_0)/L]\alpha = (t_1 - t_0)/L. Vivamus laoreet erat purus,
malesuada a. Morbi at est sed mauris blandit congue.

\fB[C10a.mde]\fP

| \fBFirst Header\fP | 
\fBSecond Header\fP | 

| Content Cell | 
Content \fICell\fP | 

| Content Cell | 
Content \fBCell\fP | 



\fB[C10b.mde]\fP

| \fBFirst Header\fP | 
\fBSecond Header\fP | 
\fBThird header\fP | 

| Content Cell | 
\fBCell\fP | 
\fBCell\fP | 

| Content Cell | 
\fBCell\fP | 
\fBCell\fP | 


\fB[C10c.mde]\fP

| \fBFirst Header\fP | 
\fBSecond Header\fP | 
\fBThird header\fP | 

| Content Cell | 
\fILong Cell\fP | 

| Content Cell | 
\fBCell\fP | 
\fBCell\fP | 

.PP
[C10d.mde]
|               | Grouping                    ||
| First Header  | Second Header | Third header |
| ------------- | ------------: | :----------: |
| Content Cell  |  \fILong Cell\fP                ||
| Content Cell  | \fBCell\fP      | \fBCell\fP     |
[ my table 1 caption ]
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a.

\fB[ my table 2 caption ]\fP

| \fB\fP | 
\fBGrouping\fP | 

| \fBFirst Header\fP | 
\fBSecond Header\fP | 
\fBThird header\fP | 

| Content Cell | 
\fILong Cell\fP | 

| Content Cell | 
\fBCell\fP | 
\fBCell\fP | 

.PP
Sed lacinia orci neque, ac facilisis tellus egestas a.
.PP
{#table3-id}[ my table 3 caption ]
| \fB\fP | 
\fBGrouping\fP | 

| \fBFirst Header\fP | 
\fBSecond Header\fP | 
\fBThird header\fP | 

| Content Cell | 
\fILong Cell\fP | 

| Content Cell | 
\fBCell\fP | 
\fBCell\fP | 


.PP
Sed lacinia orci neque, ac facilisis tellus egestas a.
.PP
|               | Grouping                    ||
| First Header  | Second Header | Third header |
| ------------- | ------------: | :----------: |
| Content Cell  |  \fILong Cell\fP                ||
| Content Cell  | \fBCell\fP      | \fBCell\fP     |
{#table4-id}[ my table 4 caption ]
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a.
.PP
[ my table 5 caption ]{#table5-id}
| \fB\fP | 
\fBGrouping\fP | 

| \fBFirst Header\fP | 
\fBSecond Header\fP | 
\fBThird header\fP | 

| Content Cell | 
\fILong Cell\fP | 

| Content Cell | 
\fBCell\fP | 
\fBCell\fP | 


.PP
Sed lacinia orci neque, ac facilisis tellus egestas a.
.PP
|               | Grouping                    ||
| First Header  | Second Header | Third header |
| ------------- | ------------: | :----------: |
| Content Cell  |  \fILong Cell\fP                ||
| Content Cell  | \fBCell\fP      | \fBCell\fP     |
[ my table 6 caption ]{#table6-id}

\fB[C10e.mde]\fP

| \fB\fP | 
\fBGrouping\fP | 

| \fBFirst Header\fP | 
\fBSecond Header\fP | 
\fBThird header\fP | 

| Content Cell | 
\fILong Cell\fP | 

| Content Cell | 
\fBCell\fP | 
\fBCell\fP | 

.PP
| New section   |   More        |         Data |
| And more      |           And more          ||
.PP
[C11.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
[\Delta = \frac{\partial U^*}{\partial F} = \frac{12F}{Eb} \int_0^L \frac{x^2}{(t_0 + \alpha x)^3} dx]\Delta = \frac{\partial U^*}{\partial F} = \frac{12F}{Eb} \int_0^L \frac{x^2}{(t_0 + \alpha x)^3} dx.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[C12.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP

.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[C2.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[C3.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a..br

Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor..br

Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in..br

Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[C4.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.

--------------------
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.

--------------------
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.

--------------------
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[C5a.mde]
.SH LOREM IPSUM
.SH DOLOR SITE AMET
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.TP sed_lacinia_orci_neque
\fBSed lacinia orci neque\fP
.RS
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.RS
.RS
.RS
.SH DOLOR SITE AMET
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.TP sed_lacinia_orci_neque_549dd39830faa
\fBSed lacinia orci neque\fP
.RS
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[C5b.mde]
.RS
.RS
.RS
.RS
.SH LOREM IPSUM
.SH DOLOR SITE AMET
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.SS Sed lacinia orci neque
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.SH DOLOR SITE AMET
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
[C6a.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id.
.RS

.EX
In pellentesque augue at ante 
.br
sagittis,<br />ut aliquam arcu velit.
.br
<p>Etiam luctus ligula sit amet libero porta ullamcorper.</p>
.br

.br
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci.
.br

.br
Nulla scelerisque elit arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et mauris lacinia pulvinar. Suspendisse potenti.
.EE
.RE
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[C6b.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id.
.RS

.EX
In pellentesque augue at ante 
.br
sagittis,<br />ut aliquam arcu velit.
.br
<p>Etiam luctus ligula sit amet libero porta ullamcorper.</p>
.br

.br
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci.
.br

.br
Nulla scelerisque elit arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et mauris lacinia pulvinar. Suspendisse potenti.
.br

.EE
.RE
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.RS

.EX
In pellentesque augue at ante 
.br
sagittis,<br />ut aliquam arcu velit.
.br

.br

.br
<p>Etiam luctus ligula sit amet libero porta ullamcorper.</p>
.br

.br

.br

.br
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci.
.br

.br
Nulla scelerisque elit arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et mauris lacinia pulvinar. Suspendisse potenti.
.br

.EE
.RE
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.RS

.EX
In pellentesque augue at ante 
.br
sagittis,<br />ut aliquam arcu velit.
.br

.br

.br
<p>Etiam luctus ligula sit amet libero porta ullamcorper.</p>
.br

.br

.br

.br
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci.
.br

.br
Nulla scelerisque elit arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et mauris lacinia pulvinar. Suspendisse potenti.
.br

.EE
.RE
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[C7.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue.
.RS

"
.PP
  Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
  ornare, id sollicitudin tellus facilisis. \fBFusce velitdiet\fP dignissim augue, a sollicitudin 
  ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo.
"
.RE
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue.
.RS

"
.PP
  Sed lacinia orci neque, ac facilisis
  ornare, id sollicitudin tellus facilisis. \fBFusce velitdiet\fP dignissim augue, a sollicitudin 
  ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo.
"
.RE
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue.
.RS

"
.PP
  Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
    ornare, id sollicitudin tellus facilisis. \fBFusce velitdiet\fP dignissim augue, a sollicitudin 
    ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo.
"
.RE
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue.
.RS

"
.PP
  Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
  ornare, id sollicitudin tellus facilisis. \fBFusce velitdiet\fP dignissim augue, a sollicitudin 
  ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo.
"
.RE
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue.
.RS

"
.PP
  Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
    ornare, id sollicitudin tellus facilisis. \fBFusce velitdiet\fP dignissim augue, a sollicitudin 
    ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo.
  .RS
  
  "
  .PP
    Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus
       ornare, id sollicitudin tellus facilisis. \fBFusce velitdiet\fP dignissim augue, a sollicitudin 
       ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo.
  "
  .RE
  .PP
  Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus
    ornare, id sollicitudin tellus facilisis. \fBFusce velitdiet\fP dignissim augue, a sollicitudin 
    ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo.
"
.RE
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
[C8a.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac.
.RS
.IP \(bu 
Vivamus laoreet erat purus, \fBid tincidunt ipsum\fP
malesuada a.
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.
.RE
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac.
.RS
.IP \(bu 
Vivamus laoreet erat purus, \fBid tincidunt ipsum\fP 
malesuada a:

.RS
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.

.RS
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci \fBid felis consectetur\fP auctor.

.RS
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.
.RE

.IP \(bu 
Morbi at est sed mauris blandit congue.
.RE

.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.
.RE

.IP \(bu 
Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a
.RE
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac.
.RS
.IP \(bu 
.PP
Vivamus laoreet erat purus, \fBid tincidunt ipsum\fP
malesuada a:
.PP
Morbi at est sed mauris blandit congue.

.IP \(bu 
.PP
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor.
.PP
Sed malesuada orci \fBid felis consectetur\fP auctor.
.RS
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 

Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor.

Sed malesuada orci id felis consectetur auctor.

.IP \(bu 
Morbi at est sed mauris blandit congue.
.RE

.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 

Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec

sapien sodales eleifend eget non tortor.

Sed malesuada orci id felis consectetur auctor.

.IP \(bu 

Vivamus laoreet erat purus

id tincidunt ipsum

malesuada a

.RE
.PP
Vestibulum laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
).
[C8b.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac.
.RS
.IP \(bu 
Vivamus laoreet erat purus, \fBid tincidunt ipsum\fP
malesuada a.
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.
.RE
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac.
.RS
.IP \(bu 
Vivamus laoreet erat purus, \fBid tincidunt ipsum\fP 
malesuada a:

.RS
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.

.RS
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci \fBid felis consectetur\fP auctor.
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.
.IP \(bu 
Morbi at est sed mauris blandit congue.
.RE

.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.
.RE

.IP \(bu 
Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a
.RE
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac.
.RS
.IP \(bu 
.PP
Vivamus laoreet erat purus, \fBid tincidunt ipsum\fP
malesuada a:
.PP
Morbi at est sed mauris blandit congue.

.IP \(bu 
.PP
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor.
.PP
Sed malesuada orci \fBid felis consectetur\fP auctor.
.RS
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 

Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor.

Sed malesuada orci id felis consectetur auctor.

.IP \(bu 
Morbi at est sed mauris blandit congue.
.RE

.IP \(bu 
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.
.IP \(bu 
Morbi at est sed mauris blandit congue.
.IP \(bu 

Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec

sapien sodales eleifend eget non tortor.

Sed malesuada orci id felis consectetur auctor.

.IP \(bu 

Vivamus laoreet erat purus

id tincidunt ipsum

malesuada a

.RE
.PP
Vestibulum laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
).
.PP
1&#46; Lorem ipsum
1&#46; Lorem ipsum
1&#46; Lorem ipsum
.PP
[C9.mde]
In pellentesque augue at ante sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper.
.TP
Lorem ipsum dolor sit amet
consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a.
.TP
Morbi at est sed mauris blandit congue
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id.
.PP
In pellentesque augue at ante sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper.
.TP
Lorem ipsum dolor sit amet
consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a.
Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id.
.PP
In pellentesque augue at ante sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper.
.TP
Lorem ipsum dolor sit amet
consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a.

Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id.
.PP
In pellentesque augue at ante sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper.
.PP
[D1.mde]
author: info@aboutmde.org
mymeta1: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
mymeta2: Sed lacinia orci neque, ac facilisis tellus egestas a.
Etiam iaculis nunc non metus ornare, id sollicitudin tellus facilisis.
Fusce velitdiet dignissim augue, a sollicitudin
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac.
.PP
[%mymeta1] Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor.
.PP
Vestibulum [%mymeta2] laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
[D2.mde]
Lorem \fIipsum dolor\fP sit amet, \fBconsectetur adipiscing\fP elit. Suspendisse \fBconvallis erat nisl\fP, 
scelerisque ornareipsumegestas ac.
.PP
Lorem &#42;ipsum dolor&#42; sit amet, \fBconsectetur adipiscing\fP elit. Suspendisse &#95;&#95;convallis erat nisl&#95;&#95;, 
scelerisque ornareipsumegestas ac.
.TP
Vivamus laoreet erat purus
Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor.
.PP
Vivamus laoreet erat purus
&#58;   Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
    eleifend eget non tortor.
.SH SED MALESUADA ORCI ID FELIS CONSECTETUR AUCTOR
.PP
&#35;&#35; Sed malesuada orci id felis consectetur auctor
.RS
.IP \(bu 
laoreet sapien lorem
.IP \(bu 
vitae ornare nulla convallis id
.RE
.PP
Etiam luctus ligula sit amet libero porta ullamcorper.
.PP
&#45;   laoreet sapien lorem
&#45;   vitae ornare nulla convallis id
.PP
Etiam luctus ligula sit amet libero porta ullamcorper.
.RS
.IP \(bu 
laoreet sapien lorem
.IP \(bu 
vitae ornare nulla convallis id
.RE
.PP
Etiam luctus ligula sit amet libero porta ullamcorper.
.PP
1&#46;   laoreet sapien lorem
1&#46;   vitae ornare nulla convallis id
.PP
Sed lacinia orci neque, ac `\fSfacilisis tellus egestas\fP` a. Etiam iaculis nunc non metus.
.PP
Sed lacinia orci neque, ac &#96;facilisis tellus egestas&#96; a. Etiam iaculis nunc non metus.
| \fBFirst Header\fP | 
\fBSecond Header\fP | 

| Content Cell | 
Content \fICell\fP | 

.PP
&#124; First Header  | Second Header    |
&#124; ------------- | ---------------- |
&#124; Content Cell  | Content \fICell\fP   |
.PP
Lorem ipsum dolor sit amet <http://aboutmde.org/loremipsum/lorem-ipsum.html> elit.
.PP
Lorem ipsum &#91;dolor sit amet&#93;[http://aboutmde.org/loremipsum/lorem-ipsum.html]http://aboutmde.org/loremipsum/lorem-ipsum.html elit.
.PP
[D5a.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit2 <#fng:elit>. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien 
eleifend eget non tortor. \fBSed malesuada orci\fP id felis consectetur auctor4 <#fng:orci>. Vestibulum
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci6 <#fng:orci>.
.PP
Nulla scelerisque elit arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. 
Vestibulum aliquam quam et mauris lacinia pulvinar. Suspendisse potenti.
.PP
[D5b.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit8 <#fng:elit>. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien 
eleifend eget non tortor. \fBSed malesuada orci\fP id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci10 <#fng:orci>.
.PP
Nulla scelerisque elit arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. 
Vestibulum aliquam quam et mauris lacinia pulvinar. Suspendisse potenti.
.PP
[D5c.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit[][#elit]. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien
eleifend eget non tortor. \fBSed malesuada orci\fP id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci.
.PP
Nulla scelerisque elit arcu, gravida interdum risus cursus vel [p. 666, [^vel]]. Sed non ipsum nulla. 
Vestibulum aliquam quam et mauris lacinia pulvinar. Suspendisse potenti.
.PP
[D6a.mde]
.SH LOREM IPSUM
.SH DOLOR SITE AMET {#AMET .LOREMIPSUMHEADER}
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a.
.PP
Morbi at est sed mauris blandit <http://aboutmde.org/loremipsum/lorem-ipsum.html>{#blandit .loremipsumlink} congue.
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci <#anchor>.
.PP
~~~{#orcicodeblock}
In pellentesque augue at ante 
sagittis,<br />ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
).
<p>Etiam luctus ligula sit amet libero porta ullamcorper.</p>.PP
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci.
.PP
Nulla scelerisque elit arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et mauris lacinia pulvinar. Suspendisse potenti.
.RS

.EX
.br
.br
Nulla scelerisque elit arcu, [gravida interdum][Lorem ipsum link] risus cursus vel. Sed non ipsum nulla.
.br
Vestibulum aliquam quam et 
.br
mauris lacinia pulvinar. Suspendisse potenti.
.br

.br
### Sed lacinia orci neque {#neque .loremipsumheader .loremipsumtest}
.br

.br
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
.br
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
.br
ligula sagittis in. ![Nam dolor leo][Lorem ipsum image], placerateu odioet, fermentum hendrerit justo. Fusce 
.br
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
.br
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus. 
.br

.br
Dolor site amet
.br
---------------
.br

.br
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
.br
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
.br
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit nec sapien sodales 
.br
eleifend eget non tortor.
.br

.br
![Lorem ipsum](http://aboutmde.org/loremipsum/lorem-ipsum.jpg){.loremipsumimage}
.br

.br
Sed malesuada orci id felis consectetur auctor. Vestibulum 
.br
laoreet sapien lorem, vitae ornare nulla convallis id. In pellentesque augue at ante 
.br
sagittis, ut aliquam arcu velit. Etiam luctus ligula sit amet libero porta ullamcorper. 
.br
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci.{#anchor}
.br

.br
~~~html{#orcicodeblock}
.br
In pellentesque augue at ante 
.br
sagittis,<br />ut aliquam arcu velit.
.br
<p>Etiam luctus ligula sit amet libero porta ullamcorper.</p>
.br

.br
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci.
.br

.br
Nulla scelerisque elit arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et mauris lacinia pulvinar. Suspendisse potenti.
.br

.EE
.RE
.PP
Nulla scelerisque elit arcu, gravida interdum risus cursus vel. Sed non ipsum nulla.
Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
[Lorem ipsum link]: http://aboutmde.org/loremipsum/lorem-ipsum.html {#ref1 .loremipsumlink}
[Lorem ipsum image]: http://aboutmde.org/loremipsum/lorem-ipsum.jpg {#ref2 .loremipsumimage}
.PP
[D8a.mde]
.SH LOREM IPSUM
.SH DOLOR SITE AMET
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue.
.SS Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
.PP
Eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id.
.TP in_pellentesque_augue_at_ante
\fBIn pellentesque augue at ante\fP
.RS
.PP
Sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.RS
.RS
.SS Sed lacinia orci neque
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis.
.TP fusce_velitdiet
\fBFusce velitdiet\fP
.RS
.PP
Dignissim augue, a sollicitudin ligula sagittis in. Nam dolor leo, placerateu odioet. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.RS
.RS
.RS
.RS
.SH DOLOR SITE AMET
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue.
.SS Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
.PP
Eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id.
.TP in_pellentesque_augue_at_ante_549dd39832967
\fBIn pellentesque augue at ante\fP
.RS
.PP
Sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.RE
.RE
.RE
.TP sed_lacinia_orci_neque_549dd39832aee
\fBSed lacinia orci neque\fP
.RS
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis.
.RE
.TP ___fusce_velitdiet
\fB#### Fusce velitdiet\fP
.RS
.PP
Dignissim augue, a sollicitudin ligula sagittis in. Nam dolor leo, placerateu odioet. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.

--------------------
.RS
.RS
.RS
.RS
.RS
.RS
.SH LOREM IPSUM
.SH DOLOR SITE AMET
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue.
.SS Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
.PP
Eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id.
.TP in_pellentesque_augue_at_ante_549dd39833310
\fBIn pellentesque augue at ante\fP
.RS
.PP
Sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.RS
.RS
.SS Sed lacinia orci neque
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis.
.TP fusce_velitdiet_549dd39833615
\fBFusce velitdiet\fP
.RS
.PP
Dignissim augue, a sollicitudin ligula sagittis in. Nam dolor leo, placerateu odioet. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.RS
.RS
.RS
.RS
.SH DOLOR SITE AMET
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue.
.SS Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales
.PP
Eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id.
.TP in_pellentesque_augue_at_ante_549dd39833ae7
\fBIn pellentesque augue at ante\fP
.RS
.PP
Sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit amet libero porta ullamcorper. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.RE
.RE
.RE
.TP sed_lacinia_orci_neque_549dd39833c6e
\fBSed lacinia orci neque\fP
.RS
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis.
.RE
.TP ___fusce_velitdiet_549dd39833df3
\fB#### Fusce velitdiet\fP
.RS
.PP
Dignissim augue, a sollicitudin ligula sagittis in. Nam dolor leo, placerateu odioet. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[D8b.mde]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis erat nisl, 
scelerisque ornareipsumegestas ac. Vivamus laoreet erat purus, id tincidunt ipsum 
malesuada a. Morbi at est sed mauris blandit congue. Donec sed velit (
.SM Lorem ipsum dolor sit amet
) nec sapien sodales 
eleifend eget non tortor. Sed malesuada orci id felis consectetur auctor. Vestibulum 
laoreet sapien lorem, vitae ornare nulla convallis id.
| \fBFirst Header\fP | 
\fBSecond Header\fP | 
\fBThird header\fP | 

| Content Cell | 
\fILong Cell\fP | 

| Content Cell | 
\fBCell\fP | 
\fBCell\fP | 

.PP
In pellentesque augue at ante sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP

.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. Nam dolor leo, placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
| First Header  | Second Header | Third header |
| ------------- | ------------: | :----------: |
| Content Cell  |  \fILong Cell\fP                ||
| Content Cell  | \fBCell\fP      | \fBCell\fP     |
{#tableid}
.PP
In pellentesque augue at ante sagittis, ut aliquam arcu velit (
.SM Lorem ipsum dolor sit amet
). Etiam luctus ligula sit. 
Phasellus nisi tortor, sodaleseget laciniaid, tincidunt ac orci. Nulla scelerisque elit 
arcu, gravida interdum risus cursus vel. Sed non ipsum nulla. Vestibulum aliquam quam et 
mauris lacinia pulvinar. Suspendisse potenti.
.PP
{#imageid}
.PP
Sed lacinia orci neque, ac facilisis tellus egestas a. Etiam iaculis nunc non metus 
ornare, id sollicitudin tellus facilisis. Fusce velitdiet dignissim augue, a sollicitudin 
ligula sagittis in. ![Nam dolor leo][Lorem ipsum image], placerateu odioet, fermentum hendrerit justo. Fusce 
eu lorem sed leo gravida facilisis. Nunc tincidunt vehicula ullamcorper. Phasellus aliquet 
orci eu eros tincidunt tincidunt. Morbi imperdiet dictum dapibus.
.PP
[Lorem ipsum image]: http://aboutmde.org/loremipsum/lorem-ipsum.jpg {#ref2 .loremipsumimage}
.PP
[MDE_syntax.mde]
Title:   Full test of MDE syntax
Author:  aboutmde.org
Comment: This is a comment intended to demonstrate
         metadata that spans multiple lines, yet
         is treated as a single value..br

Test:    And this is a new key-value pair
.RS
.RS
.RS
.RS
.RS
.RS
.SH THE \fIMarkdown Extended\fP SYNTAX
.PP
{% TOC %}
.SH BLOCKS AND STRUCTURAL ELEMENTS
.PP
Titles: `\fS#my title level 1\fP` or `\fS###my title level 3\fP` (example: just above)
.PP
Paragraphs: just pass a line (exemple this line ...)
.PP
Pre-formatted: begin lines with 4 spaces (example this block)
.RS

.EX
    pre formed content
.EE
.RE
.PP
Blockquotes and citations: begin lines by '>'
.RS

.EX
> my citation
.EE
.RE
.PP
Example:
.RS

"
.PP
  My citation
  .PP
  With a paragraph and some `\fScode\fP`
  .RS
  
  .EX
  and even a preformatted string
  .EE
  .RE
"
.RE
.PP
Adding a reference URL to blockquote:
.RS

.EX
> (http://example.com) this is my citation extracted from the content
.br
> of the page at http://example.com URL
.EE
.RE
.PP
Example:
.RS

"
.PP
  this is my citation extracted from the content
  of the page at http://example.com URL
"
.RE
.PP
An horizontal rule: 3 or more hyphens, asterisks or underscores on a line:
.RS

.EX
----
.EE
.RE
.PP
Example:

--------------------
.PP
Fenced code block: a line of tildes (at least 3)
.RS

.EX
~~~~
.br
My code here
.br
~~~~
.EE
.RE
.PP
Example:
.RS

.EX
My code here
.br

.EE
.RE
.PP
Fenced code block with information about the language: a line of tildes (at least 3) followed by language name (without space)
.RS

.EX
~~~~html
.br
My code here
.br
~~~~
.EE
.RE
.PP
Example:
.RS

.EX
My code here
.br

.EE
.RE
.SH TYPOGRAPHY
.PP
Bold text: `\fS**bolded content**\fP` or `\fS__bolded content__\fP` (example: \fBbold text\fP)
.PP
Italic text: `\fS*italic content*\fP` or `\fS_italic content_\fP` (example: \fIitalic text\fP)
.PP
A code span: `\fS`function()`\fP` (example: `\fSfunction()\fP`)
.PP
Allowing underscores in emphasis: `\fS__my_underscored_bold_word__\fP` (example: \fBmy_underscored_bold_word\fP)
.PP
An abbreviation:
.RS

.EX
*[HTML]: Hyper Text Markup Language
.EE
.RE
.PP
Example: A text whit HTML (
.SM Hyper Text Markup Language
) expression.
.SH LINKS AND IMAGES
.PP
Automatic links: `\fS<http://example.com/>\fP` and `\fS<address@email.com>\fP` (example: <http://example.com/> and <address@email.com>)
.PP
An hypertext link: `\fS[link text](http://example.com/ "Optional link title")\fP` (example: link text <http://example.com/>)
.PP
A referenced hypertext link: `\fS[link text] [myid]\fP` and after the paragraph, anywhere in the document `\fS[myid]: http://example.com/ "Optional link title"\fP` (example: link text <http://example.com/>)
.PP
An embedded image: `\fS![Alt text](http://upload.wikimedia.org/wikipedia/commons/7/70/Example.png "Optional image title")\fP` (example: )
.PP
A referrenced embedded image: `\fS![Alt text][myimageid]\fP` and after the paragraph, anywhere in the document `\fS[myimageid]: http://upload.wikimedia.org/wikipedia/commons/7/70/Example.png "Optional image title"\fP` (example: )
.PP
An inpage link: `\fS[link text](#anchor)\fP` will return to `\fS# my title {#anchor}\fP` (example: link text <#myanchor>)
.PP
An self-reference link: `\fS[link text][anchor]\fP` will refer to `\fSMy text[anchor]\fP` (example:  [link text, [^mynewanchor]] or [atitleanchor][])
.PP
A referenced link image with attributes: `\fS[mylink][]\fP` will refer to reference `\fS[mylink]: http://example.com/ "Optional title" class=external style="border: solid black 1px;"\fP`
.PP
Example: mylink <http://example.com/> and mylink2 <http://example.com/> and mylink3 <http://example.com/>
.PP
An embedded image with attributes: `\fS![myimage][]\fP` will refer to reference `\fS[myimage]: http://upload.wikimedia.org/wikipedia/commons/7/70/Example.png "Optional image title" width=40 height=40\fP`
.PP
Example: 
.PP
A referenced embedded image with attributes: `\fS![alternative text][myimage]\fP` will refer to reference `\fS[myimage]: http://upload.wikimedia.org/wikipedia/commons/7/70/Example.png "Optional image title" width=40 height=40\fP`
.PP
Example: 
.RS

.EX
style="border: solid black 1px;"
.EE
.RE
.SH HTML (
.SM Hyper Text Markup Language
)
.PP
A list: begin each entry by an asterisk, a plus or an hyphen followed by 3 spaces
.RS

.EX
-   first item
.br
*   second item
.br
    - first sub-item
.br
    * second sub-item
.br
-   third item
.EE
.RE
.PP
Example:
.RS
.IP \(bu 
first item
.IP \(bu 
second item

.RS
.IP \(bu 
first sub-item
.IP \(bu 
second sub-item
.RE

.IP \(bu 
third item
.RE
.PP
An ordered list: begin each entry by a number followed by a dot and 3 spaces
.RS

.EX
1.   first item
.br
1.   second item
.br
    1. first sub-item
.br
    1. second sub-item
.br
2.   third item
.EE
.RE
.PP
Example:
.RS
.IP \(bu 
first item
.IP \(bu 
second item

.RS
.IP \(bu 
first sub-item
.IP \(bu 
second sub-item
.RE

.IP \(bu 
third item
.RE
.PP
A table:
.RS

.EX
| First Header  | Second Header |
.br
| ------------- | ------------: |
.br
| Content Cell  | Content Cell  |
.br
| Content Cell  | Content Cell  |
.EE
.RE
.PP
or (without leading pipe) :
.RS

.EX
First Header  | Second Header |
.br
------------- | ------------: |
.br
Content Cell  | Content Cell  |
.br
Content Cell  | Content Cell  |
.EE
.RE
.PP
or (not constant spaces) :
.RS

.EX
| First Header | Second Header |
.br
| ------------ | ------------: |
.br
| Cell | Cell |
.br
| Cell | Cell |
.EE
.RE
.PP
Example:
| \fBFirst Header\fP | 
\fBSecond Header\fP | 

| Content Cell | 
Content Cell | 

| Content Cell | 
Content Cell | 

.PP
and
| \fBFirst Header\fP | 
\fBSecond Header\fP | 

| Content Cell | 
Content Cell | 

| Content Cell | 
Content Cell | 

.PP
and
| \fBFirst Header\fP | 
\fBSecond Header\fP | 

| Cell | 
Cell | 

| Cell | 
Cell | 

.PP
A table with multi-bodies:
.RS

.EX
|             | Grouping                    ||
.br
First Header  | Second Header | Third header |
.br
------------- | ------------: | :----------: |
.br
Content Cell  |  *Long Cell*                ||
.br
Content Cell  | **Cell**      | **Cell**     |
.br

.br
New section   |   More        |         Data |
.br
And more      |           And more          ||
.EE
.RE
.PP
Example:
| \fB\fP | 
\fBGrouping\fP | 

| \fBFirst Header\fP | 
\fBSecond Header\fP | 
\fBThird header\fP | 

| Content Cell | 
\fILong Cell\fP | 

| Content Cell | 
\fBCell\fP | 
\fBCell\fP | 

.PP
New section   |   More        |         Data |
And more      |           And more          ||
.PP
New example:
.RS

.EX
[prototype *table*]
.br
|             | Grouping                    ||
.br
First Header  | Second Header | Third header |
.br
First comment  | Second comment | Third comment |
.br
------------- | ------------: | :----------: |
.br
Content Cell  |  *Long Cell*                ||
.br
Content Cell  | **Cell**      | **Cell**     |
.br
New section   |   More        |         Data |
.br
And more      |           And more          ||
.br
And more                     || And more     |
.EE
.RE

\fB[prototype \fItable\fP]\fP

| \fB\fP | 
\fBGrouping\fP | 

| \fBFirst Header\fP | 
\fBSecond Header\fP | 
\fBThird header\fP | 

| \fBFirst comment\fP | 
\fBSecond comment\fP | 
\fBThird comment\fP | 

| Content Cell | 
\fILong Cell\fP | 

| Content Cell | 
\fBCell\fP | 
\fBCell\fP | 

| New section | 
More | 
Data | 

| And more | 
And more | 

| And more | 
And more | 

.PP
Same example with caption after the table:
.PP
|             | Grouping                    ||
First Header  | Second Header | Third header |
First comment  | Second comment | Third comment |
------------- | ------------: | :----------: |
Content Cell  |  \fILong Cell\fP                ||
Content Cell  | \fBCell\fP      | \fBCell\fP     |
New section   |   More        |         Data |
And more      |           And more          ||
And more                     || And more     |
[prototype \fItable\fP]
.PP
A definition:
.RS

.EX
Apple
.br
:   Pomaceous fruit of plants of the genus Malus in 
.br
    the family Rosaceae.
.EE
.RE
.PP
Example:
.TP
Term 1
This is a definition with two paragraphs. Lorem ipsum 
dolor sit amet, consectetuer adipiscing elit. Aliquam 
hendrerit mi posuere lectus.

Vestibulum enim wisi, viverra nec, fringilla in, laoreet
vitae, risus.
Second definition for term 1, also wrapped in a paragraph
because of the blank line preceding it.
.TP
Term 2
.PP
This definition has a code block, a blockquote and a list.
.RS

.EX
code block.
.EE
.RE
.RS

"
.PP
  block quote
  on two lines.
"
.RE
.RS
.IP \(bu 
first list item
.IP \(bu 
second list item
.RE
.PP
A footnote:
.RS

.EX
That's some text with a footnote.[^1]
.br

.br
[^1]: And that's the footnote.
.EE
.RE
.PP
Example: That's some11 <#fn:2> text with three footnotes.12 <#fn:1>13 <#fn:3>
.PP
Citations : like footnote begining by a sharp
.RS

.EX
This is a statement that should be attributed to
.br
its source[p. 23][#Doe:2006].
.br

.br
And following is the description of the reference to be
.br
used in the bibliography.
.br

.br
[#Doe:2006]: John Doe. *Some Big Fancy Book*.  Vanity Press, 2006.
.EE
.RE
.PP
Example:
.PP
This is a statement that should be attributed to
its source [p. 23, 14 <#fnc:Doe:2006>].
.PP
And following is the description of the reference to be
used in the bibliography.
.PP
Glossary footnotes :
.RS

.EX
[^glossaryfootnote]: glossary: term (optional sort key)
.br
    The actual definition belongs on a new line, and can continue on
.br
    just as other footnotes.
.EE
.RE
.PP
Example:
.PP
My text with a footnote ref 15 <#fng:glossaryfootnote>.
.SH TEST OF BLOCK INCLUSION
.PP
Inclusion of a third-party file content writing (\fIpath is relative to original source\fP):
.RS

.EX
<!-- ERROR while parsing /Users/pierrecassat/Sites/GitHub_projects/markdown-extended/demo/build/../../tests/inclusion-test.md : 'Source file "/Users/pierrecassat/Sites/GitHub_projects/markdown-extended/demo/build/../../tests/inclusion-test.md" not found or is not readable!' -->
.EE
.RE
.PP
Below may happend the parsed content of `\fSdemo/inclusion-test.md\fP`:

--------------------
<!-- ERROR while parsing /Users/pierrecassat/Sites/GitHub_projects/markdown-extended/demo/build/../../tests/inclusion-test.md : 'Source file "/Users/pierrecassat/Sites/GitHub_projects/markdown-extended/demo/build/../../tests/inclusion-test.md" not found or is not readable!' -->
--------------------
.PP
In case of error, the error info is written as HTML (
.SM Hyper Text Markup Language
) comment:
.RS

.EX
<!-- ERROR while parsing /Users/pierrecassat/Sites/GitHub_projects/markdown-extended/demo/build/../../tests/not-found-file.md : 'Source file "/Users/pierrecassat/Sites/GitHub_projects/markdown-extended/demo/build/../../tests/not-found-file.md" not found or is not readable!' -->
.EE
.RE

--------------------
<!-- ERROR while parsing /Users/pierrecassat/Sites/GitHub_projects/markdown-extended/demo/build/../../tests/not-found-file.md : 'Source file "/Users/pierrecassat/Sites/GitHub_projects/markdown-extended/demo/build/../../tests/not-found-file.md" not found or is not readable!' -->.RS

.EX
If you look in the HTML source, you may find here:
.br
<!-- ERROR while parsing ./not-found-file.md : 'Source file "./not-found-file.md" not found or is not readable!' -->
.EE
.RE

--------------------
.SS Anchor for tests with a specific anchor `\fS{#myanchor}\fP` ...
.SH SOME INLINE HTML (
.SM Hyper Text Markup Language
) FOR TESTS
.PP
This is a regular paragraph.
<table border="2px" cellspacing="2px" cellpadding="6px">
    <tr>
        <td>Foo</td>
        <td>*Foo*</td>
        <td>`Foo`</td>
    </tr>
</table>.PP
This is another regular paragraph, with another call of footnote 2 16 <#fn:2>.
.PP
Below is the same table as above with argument `\fSmarkdown="1"\fP`.
<table border="2px" cellspacing="2px" cellpadding="6px">.PP
<tr>
    <td>Foo</td>
    <td>\fIFoo\fP</td>
    <td>`\fSFoo\fP`</td>
</tr>
</table>.PP
This is another regular paragraph.

--------------------
.SH TEST OF MATHEMATICS
.PP
where [\alpha = (t_1 - t_0)/L]\alpha = (t_1 - t_0)/L is the rate at which the thickness increases
.PP
Putting this into Castigliano's equation, we get
[\Delta = \frac{\partial U^*}{\partial F} = \frac{12F}{Eb} \int_0^L \frac{x^2}{(t_0 + \alpha x)^3} dx]\Delta = \frac{\partial U^*}{\partial F} = \frac{12F}{Eb} \int_0^L \frac{x^2}{(t_0 + \alpha x)^3} dx.PP
[inclusion-test.mde]
At vero eos et accusamus et \fBiusto odio dignissimos ducimus qui blanditiis\fP praesentium
voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi.
.RS

"
.PP
  Sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt
      mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et
      expedita distinctio.
"
.RE
.PP
Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id
quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.
Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet
ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic
tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut
perferendis doloribus asperiores repellat.

.RS
.IP 1.
.PP
Suspendisse convallis erat nisl, \fBscelerisque ornareipsumegestas\fP ac. Vivamus 
laoreet erat purus, id tincidunt ipsum malesuada a. Morbi at est sed mauris blandit congue.

.PP
↩ <#fnref:elit>

.IP 2.
Nulla scelerisque elit arcu, gravida interdum risus cursus vel. Sed non ipsum nulla.
Vestibulum aliquam quam et mauris lacinia pulvinar. Suspendisse potenti.


↩ <#fnref:orci>

.IP 3.
And that's another footnote (the second)
on \fItwo lines\fP for test ...


↩ <#fnref:2>

.IP 4.
And that's the first footnote.

That's the second paragraph.


↩ <#fnref:1>

.IP 5.
And that's a footnote with a link <http://example.com>.


↩ <#fnref:3>

.IP 6.
John Doe. \fISome Big Fancy Book\fP.  Vanity Press, 2006.


↩ <#fncref:Doe:2006>

.IP 7.
term2

The actual definition belongs on a new line, and can continue on
just as other footnotes.


↩ <#fngref:glossaryfootnote>

.RE
