var tree = [["MarkdownExtended","MarkdownExtended.html","",
                [["API","MarkdownExtended\/API.html","",
                [["CollectionInterface","MarkdownExtended\/API\/CollectionInterface.html","",
                [        ]],["ContentInterface","MarkdownExtended\/API\/ContentInterface.html","",
                [        ]],["GamutInterface","MarkdownExtended\/API\/GamutInterface.html","",
                [        ]],["KernelInterface","MarkdownExtended\/API\/KernelInterface.html","",
                [        ]],["OutputFormatHelperInterface","MarkdownExtended\/API\/OutputFormatHelperInterface.html","",
                [        ]],["OutputFormatInterface","MarkdownExtended\/API\/OutputFormatInterface.html","",
                [        ]],["ParserInterface","MarkdownExtended\/API\/ParserInterface.html","",
                [        ]],["TemplaterInterface","MarkdownExtended\/API\/TemplaterInterface.html","",
                [        ]]        ]],["CommandLine","MarkdownExtended\/CommandLine.html","",
                [["AbstractConsole","MarkdownExtended\/CommandLine\/AbstractConsole.html","",
                [        ]],["Console","MarkdownExtended\/CommandLine\/Console.html"," < AbstractConsole",
                [        ]],["Reminders","MarkdownExtended\/CommandLine\/Reminders.html"," < AbstractConsole",
                [        ]]        ]],["Exception","MarkdownExtended\/Exception.html","",
                [["DomainException","MarkdownExtended\/Exception\/DomainException.html"," < DomainException",
                [        ]],["Exception","MarkdownExtended\/Exception\/Exception.html"," < Exception",
                [        ]],["InvalidArgumentException","MarkdownExtended\/Exception\/InvalidArgumentException.html"," < InvalidArgumentException",
                [        ]],["RuntimeException","MarkdownExtended\/Exception\/RuntimeException.html"," < RuntimeException",
                [        ]],["UnexpectedValueException","MarkdownExtended\/Exception\/UnexpectedValueException.html"," < UnexpectedValueException",
                [        ]]        ]],["Grammar","MarkdownExtended\/Grammar.html","",
                [["Filter","MarkdownExtended\/Grammar\/Filter.html","",
                [["Abbreviation","MarkdownExtended\/Grammar\/Filter\/Abbreviation.html"," < Filter",
                [        ]],["Anchor","MarkdownExtended\/Grammar\/Filter\/Anchor.html"," < Filter",
                [        ]],["AutoLink","MarkdownExtended\/Grammar\/Filter\/AutoLink.html"," < Filter",
                [        ]],["BlockInclusion","MarkdownExtended\/Grammar\/Filter\/BlockInclusion.html"," < Filter",
                [        ]],["BlockQuote","MarkdownExtended\/Grammar\/Filter\/BlockQuote.html"," < Filter",
                [        ]],["CodeBlock","MarkdownExtended\/Grammar\/Filter\/CodeBlock.html"," < Filter",
                [        ]],["DefinitionList","MarkdownExtended\/Grammar\/Filter\/DefinitionList.html"," < Filter",
                [        ]],["Emphasis","MarkdownExtended\/Grammar\/Filter\/Emphasis.html"," < Filter",
                [        ]],["FencedCodeBlock","MarkdownExtended\/Grammar\/Filter\/FencedCodeBlock.html"," < Filter",
                [        ]],["HTML","MarkdownExtended\/Grammar\/Filter\/HTML.html"," < Filter",
                [        ]],["HardBreak","MarkdownExtended\/Grammar\/Filter\/HardBreak.html"," < Filter",
                [        ]],["Header","MarkdownExtended\/Grammar\/Filter\/Header.html"," < Filter",
                [        ]],["HorizontalRule","MarkdownExtended\/Grammar\/Filter\/HorizontalRule.html"," < Filter",
                [        ]],["Image","MarkdownExtended\/Grammar\/Filter\/Image.html"," < Filter",
                [        ]],["LinkDefinition","MarkdownExtended\/Grammar\/Filter\/LinkDefinition.html"," < Filter",
                [        ]],["ListItem","MarkdownExtended\/Grammar\/Filter\/ListItem.html"," < Filter",
                [        ]],["Maths","MarkdownExtended\/Grammar\/Filter\/Maths.html"," < Filter",
                [        ]],["MetaData","MarkdownExtended\/Grammar\/Filter\/MetaData.html"," < Filter",
                [        ]],["Note","MarkdownExtended\/Grammar\/Filter\/Note.html"," < Filter",
                [        ]],["Span","MarkdownExtended\/Grammar\/Filter\/Span.html"," < Filter",
                [        ]],["Table","MarkdownExtended\/Grammar\/Filter\/Table.html"," < Filter",
                [        ]],["TableOfContents","MarkdownExtended\/Grammar\/Filter\/TableOfContents.html"," < Filter",
                [        ]]        ]],["Tool","MarkdownExtended\/Grammar\/Tool.html","",
                [["AppendEndingNewLines","MarkdownExtended\/Grammar\/Tool\/AppendEndingNewLines.html"," < Tool",
                [        ]],["Detab","MarkdownExtended\/Grammar\/Tool\/Detab.html"," < Tool",
                [        ]],["EncodeAmpAndAngle","MarkdownExtended\/Grammar\/Tool\/EncodeAmpAndAngle.html"," < Tool",
                [        ]],["EncodeAttribute","MarkdownExtended\/Grammar\/Tool\/EncodeAttribute.html"," < Tool",
                [        ]],["ExtractAttributes","MarkdownExtended\/Grammar\/Tool\/ExtractAttributes.html"," < Tool",
                [        ]],["Outdent","MarkdownExtended\/Grammar\/Tool\/Outdent.html"," < Tool",
                [        ]],["RebuildParagraph","MarkdownExtended\/Grammar\/Tool\/RebuildParagraph.html"," < Tool",
                [        ]],["RemoveUtf8Marker","MarkdownExtended\/Grammar\/Tool\/RemoveUtf8Marker.html"," < Tool",
                [        ]],["StandardizeLineEnding","MarkdownExtended\/Grammar\/Tool\/StandardizeLineEnding.html"," < Tool",
                [        ]],["StripSpacedLines","MarkdownExtended\/Grammar\/Tool\/StripSpacedLines.html"," < Tool",
                [        ]]        ]],["AbstractGamut","MarkdownExtended\/Grammar\/AbstractGamut.html","",
                [        ]],["Filter","MarkdownExtended\/Grammar\/Filter.html"," < AbstractGamut",
                [        ]],["Gamut","MarkdownExtended\/Grammar\/Gamut.html","",
                [        ]],["Tool","MarkdownExtended\/Grammar\/Tool.html"," < AbstractGamut",
                [        ]]        ]],["OutputFormat","MarkdownExtended\/OutputFormat.html","",
                [["AbstractOutputFormat","MarkdownExtended\/OutputFormat\/AbstractOutputFormat.html","",
                [        ]],["DefaultHelper","MarkdownExtended\/OutputFormat\/DefaultHelper.html","",
                [        ]],["HTML","MarkdownExtended\/OutputFormat\/HTML.html"," < AbstractOutputFormat",
                [        ]],["HTMLHelper","MarkdownExtended\/OutputFormat\/HTMLHelper.html","",
                [        ]],["Man","MarkdownExtended\/OutputFormat\/Man.html"," < AbstractOutputFormat",
                [        ]],["ManHelper","MarkdownExtended\/OutputFormat\/ManHelper.html"," < DefaultHelper",
                [        ]]        ]],["Util","MarkdownExtended\/Util.html","",
                [["Compiler","MarkdownExtended\/Util\/Compiler.html","",
                [        ]],["MenuItemIterator","MarkdownExtended\/Util\/MenuItemIterator.html"," < ArrayIterator",
                [        ]],["RecursiveMenuIterator","MarkdownExtended\/Util\/RecursiveMenuIterator.html"," < RecursiveArrayIterator",
                [        ]]        ]],["API","MarkdownExtended\/API.html","",
                [        ]],["Config","MarkdownExtended\/Config.html"," < Registry",
                [        ]],["Content","MarkdownExtended\/Content.html","",
                [        ]],["ContentCollection","MarkdownExtended\/ContentCollection.html","",
                [        ]],["Helper","MarkdownExtended\/Helper.html","",
                [        ]],["MarkdownExtended","MarkdownExtended\/MarkdownExtended.html","",
                [        ]],["OutputFormatBag","MarkdownExtended\/OutputFormatBag.html","",
                [        ]],["Parser","MarkdownExtended\/Parser.html","",
                [        ]],["Registry","MarkdownExtended\/Registry.html","",
                [        ]],["Templater","MarkdownExtended\/Templater.html","",
                [        ]]        ]],["markdown","markdown.html","",
                [["MarkdownExtendedParser","markdown\/MarkdownExtendedParser.html"," < MarkdownParser",
                [        ]],["MarkdownExtraParser","markdown\/MarkdownExtraParser.html"," < MarkdownParser",
                [        ]],["MarkdownParser","markdown\/MarkdownParser.html","",
                [        ]],["MarkdownParserCompatibilityInterface","markdown\/MarkdownParserCompatibilityInterface.html","",
                [        ]],["MultiMarkdownParser","markdown\/MultiMarkdownParser.html"," < MarkdownParser",
                [        ]]        ]]        ]

