
name: "Run tests"
run-name: "Run Unit tests & cs-fixer for validation"

on:
  push:

permissions:
  contents: read # for checkout

jobs:

  run_tests_php74:
    name: "PHP unit tests & code standards with PHP 7.4"
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install composer dependencies
        uses: php-actions/composer@v6

      - name: Run CS-Fixer
        uses: php-actions/composer@v6
        with:
          command: run cs-fixer-ci

      - name: Test the console
        run: php ./bin/markdown-extended

      - name: Run unit tests
        run: composer run test

  run_tests_php53:
    name: "PHP unit tests & code standards with PHP 5.6"
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Setup PHP 5.6
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'

      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          version: "2.2"
          php_version: "5.6"

      - name: Test the console
        run: php ./bin/markdown-extended

      - name: Run unit tests
        run: php ./bin/phpunit --no-coverage --testdox
